# Starship Configuration
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory\
$cmd_duration\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$nodejs\
$python\
$rust\
$java\
$php\
$perl\
$swift\
$dart\
$scala\
$kotlin\
$docker_context\
$kubernetes\
$character\
"""

right_format = """
[󰇥](bold fg:yellow)
"""

# Palette
palette = "deep_oceanic_next"

[palettes.deep_oceanic_next]
background = "#003b46"  
black = "#004f5e"  
bright-black = "#006374"  
grey = "#007a8a"  
light-grey = "#0093a3"  
foreground = "#dce3e8"  
white = "#e6ebf0"  
bright-white = "#f0f5f5"  
red = "#e6454b"  
orange = "#ff6a4b"  
yellow = "#ffcc66"  
green = "#85b57a"  
cyan = "#4da6a6"  
blue = "#3a82e6"  
magenta = "#8c4de6"  
pink = "#e673a3"  
darker-black = "#001114"  
darkest-black = "#000a0d"  
bright-red = "#ff5a61"  
bright-yellow = "#ffdd80"  
bright-green = "#99d8a0"  
bright-cyan = "#66cccc"  
bright-blue = "#4da6ff"  
bright-purple = "#a366ff"  

[os]
disabled = true

[directory]
truncation_length = 6
truncate_to_repo = true
style = "fg:bright-yellow bg:background"
read_only = ""
read_only_style = ""
truncation_symbol = "…/"
repo_root_style = "underline fg:yellow bg:background"

[git_branch]
symbol = ""
format = "[\ngit: ](bold fg:light-grey bg:background)[$symbol $branch](underline bold fg:light-grey bg:background)"
truncation_length = 10

# Enhanced Git Status without clean indicator
[git_status]
format = "[$all_status$ahead_behind](fg:light-grey bg:background)"
staged = "●"  # Indicates staged files
modified = "✚"  # Indicates modified files
deleted = "✖"  # Indicates deleted files
renamed = "➜"  # Indicates renamed files
untracked = "… "  # Indicates untracked files
conflicted = "≠"  # Indicates conflicts
ahead = "⇡"  # Indicates commits ahead of the remote
behind = "⇣"  # Indicates commits behind the remote
diverged = "⇕"  # Indicates commits diverged from the remote

[package]
disabled = true

[time]
disabled = true

[cmd_duration]
format = "[$duration](fg:bright-black bg:background)"

[fill]
symbol = " "

[character]
format = "\n$symbol "
error_symbol = "[✗](bold red)"


# Docker Module with Underlined Context Only
[docker_context]
format = "[\ndck: ](bold fg:grey bg:background)[$context](underline bold fg:grey bg:background)"
disabled = false

# Kubernetes Module with Underlined Context Only
[kubernetes]
format = "[\nk8s: ](bold fg:cyan bg:background)[$context](underline bold fg:cyan bg:background)"
disabled = false

# Language Modules with Underlined Versions Only
[nodejs]
format = "[ node: ](bold fg:grey bg:background)[$version](bold fg:grey bg:background underline)"
disabled = false

[python]
format = "[ python: ](bold fg:grey bg:background)[$version](bold fg:grey bg:background underline)"
disabled = false

[rust]
format = "[ rust: ](bold fg:grey bg:background)[$version](bold fg:grey bg:background underline)"
disabled = false

[java]
format = "[ java: ](bold fg:grey bg:background)[$version](bold fg:grey bg:background underline)"
disabled = false

[swift]
format = "[ swift: ](bold fg:grey bg:background)[$version](bold fg:grey bg:background underline)"
disabled = false

[dart]
format = "[ dart: ](bold fg:grey bg:background)[$version](bold fg:grey bg:background underline)"
disabled = false

[ruby]
format = "[ ruby: ](bold fg:grey bg:background)[$version](bold fg:grey bg:background underline)"
disabled = false

[scala]
format = "[ scala: ](bold fg:grey bg:background)[$version](bold fg:grey bg:background underline)"
disabled = false

[kotlin]
format = "[ kotlin: ](bold fg:grey bg:background)[$version](bold fg:grey bg:background underline)"
disabled = false

